$schema: https://docs.renovatebot.com/renovate-schema.json

extends:
  - config:best-practices
  - :semanticCommitsDisabled

# This repo is public, so prevent the Mend Renovate app from trying to create
# PRs here by setting enabled to false.
enabled: false
dependencyDashboard: false

branchPrefix: grafanarenovatebot/
commitMessagePrefix: 'chore:'
platformCommit: enabled
forkProcessing: enabled
rebaseWhen: behind-base-branch
prHourlyLimit: 0
prConcurrentLimit: 10
branchConcurrentLimit: 10
labels:
  - dependencies

# Automerge settings
automerge: true
assignAutomerge: true
assigneesFromCodeOwners: true
automergeStrategy: squash
automergeType: pr
platformAutomerge: true
pruneBranchAfterAutomerge: true

enabledManagers:
  - custom.regex
  - gomod

gomod:
  enabled: true

postUpdateOptions:
  - gomodTidyE

regex:
  pinDigests: false

packageRules:
  - matchUpdateTypes: patch
    commitMessagePrefix: "fix:"

  - matchUpdateTypes: minor
    commitMessagePrefix: "feat:"

  - matchManagers:
      - gomod
    matchUpdateTypes:
      - digest
    schedule: before 8am on monday every 2 weeks

  - matchManagers:
      - gomod
    matchPackageNames: github.com/prometheus/*
    groupName: prometheus-go

  - matchCategories:
      - docker
    pinDigests: false

customManagers:
  - customType: regex
    description: update docker versions found in versions.yaml
    managerFilePatterns:
      - /^versions\.yaml$/
    autoReplaceStringTemplate: |2
        version: {{newValue}}
        digest: {{newDigest}}
        renovate: datasource={{datasource}}{{#if (contains 'depName' currentConfig)}} depName={{depName}}{{/if}}{{#if (contains 'packageName' currentConfig)}} packageName={{packageName}}{{/if}}{{#if (contains 'versioning' currentConfig)}} versioning={{versioning}}{{/if}}
    matchStrings:
      # Match multi-line YAML structure: tool with version and digest fields
      # Format captures:
      #   - version: X.Y.Z
      #   - digest: sha256:...
      #   - renovate: datasource=docker ...
      #
      # Beware that renovate will include newlines in \s because it uses 's'.
      - |
        ^[ \t]+version:[ \t]*(?<currentValue>[^\s]+)$
        ^[ \t]+digest:[ \t]*(?<currentDigest>sha256:[a-f0-9]+)$
        ^[ \t]+renovate:[ \t]*datasource=(?<datasource>docker)(?:[ \t]+depName=(?<depName>[-_.\/\w]+))?(?:[ \t]+packageName=(?<packageName>[-_.\/\w]+))?(?:[ \t]+versioning=(?<versioning>[-_.\/\w]+))?$

  - customType: regex
    description: update versions found in versions.yaml
    managerFilePatterns:
      - /^versions\.yaml$/
    autoReplaceStringTemplate: |2
        version: {{newValue}}
        renovate: datasource={{datasource}}{{#if (contains 'depName' currentConfig)}} depName={{depName}}{{/if}}{{#if (contains 'packageName' currentConfig)}} packageName={{packageName}}{{/if}}{{#if (contains 'versioning' currentConfig)}} versioning={{versioning}}{{/if}}
    matchStrings:
      # Beware that renovate will include newlines in \s because it uses 's'.
      - |
        ^[ \t]+version:[ \t]*(?<currentValue>\S+)$
        ^[ \t]+renovate:[ \t]*datasource=(?<datasource>github-releases|github-tags|go)(?:[ \t]+depName=(?<depName>[-_.\/\w]+))?(?:[ \t]+packageName=(?<packageName>[-_.\/\w]+))(?:[ \t]+versioning=(?<versioning>[-_.\/\w]+))?$
