name: "Validate pull request"

on:
  pull_request:
    branches:
      - main
    paths:
      - Dockerfile.tmpl
      - Dockerfile.build.tmpl
      - .github/workflows/**
      - lib/**
      - Makefile
      - scripts/**
      - versions.yaml

  workflow_dispatch:

env:
  TEST_TAG: grafana/${{ github.repository }}:test

permissions:
  contents: none
  packages: none

jobs:
  validate:
    name: Validate pull request
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-tags: true
          persist-credentials: false

      - name: Unshallow
        run: git fetch --prune --tags --unshallow

      - name: Describe the current state
        run: git describe --tags --always

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=sha-${{ github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Login to GitHub Package Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Dockerfile
        run: make Dockerfile Dockerfile.build

      - name: Build auxiliary image and export to docker
        uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 # v6.17.0
        with:
          context: .
          file: ./Dockerfile.build
          push: false
          load: true
          tags: binaries:local
          build-args: |
            TARGET_GOOS=linux
            TARGET_GOARCH=amd64
          cache-from: type=gha,scope=build-linux-amd64

      - name: Capture binaries
        run: |
          ./scripts/build-os-arch --image binaries:local --no-build linux amd64

      - name: Build container image and export to Docker
        uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 # v6.17.0
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha,scope=final

      - name: Test container image
        run: |
          docker run --rm ghcr.io/${{ github.repository }}:sha-${{ github.sha }} image-test

      - name: Lint GitHub Actions workflows
        run: ./dist/linux-amd64/actionlint
